CREATE TABLE IF NOT EXISTS source_customers (
    id integer PRIMARY KEY,
    external_id text NOT NULL UNIQUE,
    email text,
    full_name text NOT NULL,
    status text NOT NULL DEFAULT 'active',
    phone text,
    updated_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS source_orders (
    id integer PRIMARY KEY,
    external_order_id text NOT NULL UNIQUE,
    customer_external_id text,
    product_sku text,
    quantity integer,
    total_amount numeric(12, 2),
    status text NOT NULL,
    updated_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS source_inventory (
    id integer PRIMARY KEY,
    sku text NOT NULL,
    warehouse_code text NOT NULL,
    quantity_available integer,
    reorder_point integer,
    updated_at timestamptz NOT NULL,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    UNIQUE (sku, warehouse_code)
);

CREATE TABLE IF NOT EXISTS customer_reference (
    external_id text PRIMARY KEY,
    segment text NOT NULL,
    region text NOT NULL,
    active boolean NOT NULL,
    updated_at timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS product_reference (
    sku text PRIMARY KEY,
    product_name text NOT NULL,
    category text NOT NULL,
    unit_price numeric(12, 2) NOT NULL,
    active boolean NOT NULL,
    updated_at timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS dest_customers (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id text NOT NULL UNIQUE,
    email text NOT NULL UNIQUE,
    full_name text NOT NULL,
    segment text,
    source_updated_at timestamptz,
    synced_at timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS dest_orders (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_order_id text NOT NULL UNIQUE,
    customer_external_id text NOT NULL,
    product_sku text NOT NULL,
    quantity integer NOT NULL CHECK (quantity > 0),
    total_amount numeric(12, 2) NOT NULL CHECK (total_amount >= 0),
    status text NOT NULL,
    synced_at timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS inventory_snapshot (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku text NOT NULL,
    warehouse_code text NOT NULL,
    quantity_available integer NOT NULL CHECK (quantity_available >= 0),
    snapshot_at timestamptz NOT NULL,
    sync_source text NOT NULL,
    UNIQUE (sku, warehouse_code, sync_source)
);

CREATE INDEX IF NOT EXISTS idx_source_customers_updated_at ON source_customers (updated_at, id);
CREATE INDEX IF NOT EXISTS idx_source_orders_updated_at ON source_orders (updated_at, id);
CREATE INDEX IF NOT EXISTS idx_source_inventory_updated_at ON source_inventory (updated_at, id);
